### ISSUE TITLE
Ability for user to submit a link for a YouTube video to analyze its audio 

### ISSUE THREAD

**Issue by Alyssa-Webb** [Alyssa-Webb/Audionyx#1]
Create/obtain API's to convert any user submitted links for YouTube into mp3's for our program to intake. This will allow the user to enter various links and have audio converted from there.

**Comment by cosc5789** [comment]
Finished youtube link to MP3 converter rough draft. Currently, it converts a link in the code and just saves the mp3 file, but I will change it to accept user input and do other things with the converted file.
