### ISSUE TITLE
Ability to register

### ISSUE THREAD

**Issue by agsi1185** [Alyssa-Webb/Audionyx#15]
Register page welcomes new user to Audionyx, allows the user to login if they have an account. User cannot access Audionyx without an account.

Acceptance Criteria: As a user I should be able to register for an account and access the webpage. If I have an account, I should be able to login to my account. If I make an account, and I try replicating the same username, I should not be able to.

**Comment by HunterFroemming** [comment]
Base Registration Page is completed, need to create CSS for it.

**Comment by HunterFroemming** [comment]
css linked
